queue_rules:
  - name: default
    conditions:
      - '#approved-reviews-by>=1'

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=main
      - '#approved-reviews-by>=1'
    actions:
      merge:
        method: merge
      queue:
        name: default
        update_method: rebase
